using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;


namespace McMDK2.Core.Data
{
    [DataContract]
    public class ItemData : ICloneable
    {
        [DataMember]
        public string Name { set; get; }

        // This property should be generated by Guid.NewGuid();
        [DataMember]
        public string Id { set; get; }

        [DataMember]
        public string PluginId { set; get; }

        [DataMember]
        public string PluginVersion { set; get; }

        [DataMember]
        public Dictionary<string, object> Properties { set; get; }

        public object Clone()
        {
            var obj = new ItemData();
            obj.Name = this.Name;
            obj.Id = this.Id;
            obj.PluginId = this.PluginId;
            obj.PluginVersion = this.PluginVersion;
            obj.Properties = new Dictionary<string, object>(this.Properties);
            return obj;
        }
    }
}
