using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;


namespace McMDK2.Core.Data
{
    [DataContract]
    public class ItemData
    {
        [DataMember]
        public string Name { set; get; }

        // This property should be generated by Guid.NewGuid();
        [DataMember]
        public string Id { set; get; }

        [DataMember]
        public string PluginId { set; get; }

        [DataMember]
        public string PluginVersion { set; get; }

        [DataMember]
        public Dictionary<string, object> Properties { set; get; }
    }
}
