using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

#pragma warning disable 1591

namespace McMDK2.Core.Data
{
    /// <summary>
    /// McMDK2 Projectの各アイテム(*.mod)のデータを保持します。
    /// </summary>
    [DataContract]
    public class ItemData : ICloneable
    {
        /// <summary>
        /// アイテム名を設定します。
        /// </summary>
        [DataMember]
        public string Name { set; get; }


        // This property should be generated by Guid.NewGuid();
        /// <summary>
        /// アイテムごとの固有IDを設定します。
        /// </summary>
        [DataMember]
        public string Id { set; get; }

        /// <summary>
        /// アイテムの属するPluginIDを設定します。
        /// </summary>
        [DataMember]
        public string PluginId { set; get; }

        /// <summary>
        /// アイテムが生成された時点のPluginのバージョンを設定します。
        /// </summary>
        [DataMember]
        public string PluginVersion { set; get; }

        /// <summary>
        /// アイテムのプロパティを設定します。
        /// </summary>
        [DataMember]
        public Dictionary<string, object> Properties { set; get; }

        public object Clone()
        {
            var obj = new ItemData();
            obj.Name = this.Name;
            obj.Id = this.Id;
            obj.PluginId = this.PluginId;
            obj.PluginVersion = this.PluginVersion;
            obj.Properties = new Dictionary<string, object>(this.Properties);
            return obj;
        }
    }
}
